environment = "local"

GOOGLE_CLIENT_ID = "998004507032-v951llput8fnt7tq86ciceb8vn856m8c.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "https://coronationbakery.streamlit.app/callback"
